<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Capturing Screenshot]]>
    </line>
    <line>
      <![CDATA[Login successfully executed!]]>
    </line>
    <line>
      <![CDATA[<a target ="_blank" href=error>Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target ="_blank" href=error>Screenshot</a>]]>
    </line>
  </reporter-output>
  <suite started-at="2021-11-28T12:34:43Z" name="Data Driven Basics" finished-at="2021-11-28T12:34:58Z" duration-ms="14995">
    <groups>
    </groups>
    <test started-at="2021-11-28T12:34:43Z" name="Login Test" finished-at="2021-11-28T12:34:44Z" duration-ms="847">
      <class name="testCases.LoginTest">
        <test-method signature="loginAsBankManager()[pri:0, instance:testCases.LoginTest@1a6c1270]" started-at="2021-11-28T12:34:43Z" name="loginAsBankManager" finished-at="2021-11-28T12:34:44Z" duration-ms="832" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAsBankManager -->
      </class> <!-- testCases.LoginTest -->
    </test> <!-- Login Test -->
    <test started-at="2021-11-28T12:34:44Z" name="LAdd Customer Test" finished-at="2021-11-28T12:34:58Z" duration-ms="14121">
      <class name="testCases.AddCustomerTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testCases.AddCustomerTest@324a0017]" started-at="2021-11-28T12:34:18Z" name="setUp" finished-at="2021-11-28T12:34:43Z" duration-ms="25576" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="addCustomer(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testCases.AddCustomerTest@324a0017]" started-at="2021-11-28T12:34:44Z" name="addCustomer" data-provider="getData" finished-at="2021-11-28T12:34:49Z" duration-ms="4705" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Anne]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Zimmermann]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[89046-305]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Customer added successfully]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Customer not added successfully]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Customer not added successfully
at org.testng.Assert.fail(Assert.java:96)
at testCases.AddCustomerTest.addCustomer(AddCustomerTest.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Capturing Screenshot]]>
            </line>
            <line>
              <![CDATA[Login successfully executed!]]>
            </line>
            <line>
              <![CDATA[<a target ="_blank" href=error>Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target ="_blank" href=error>Screenshot</a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomer -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testCases.AddCustomerTest@324a0017]" started-at="2021-11-28T12:34:58Z" name="tearDown" finished-at="2021-11-28T12:34:59Z" duration-ms="1046" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.AddCustomerTest -->
    </test> <!-- LAdd Customer Test -->
  </suite> <!-- Data Driven Basics -->
</testng-results>
